export const GET_PROMOTIONS: "GET_PROMOTIONS" = "GET_PROMOTIONS";
export const POST_PROMOTIONS: "POST_PROMOTIONS" = "POST_PROMOTIONS";
export const HIDE_SUCCESS_MESSAGE: "HIDE_SUCCESS_MESSAGE" =
  "HIDE_SUCCESS_MESSAGE";
